import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import Hero from "@/components/sections/Hero";
import SpotLight from "@/components/sections/SpotLight";
import Events from "@/components/sections/Events";
import Explore from "@/components/sections/Explore";
import Studies from "@/components/sections/Studies";
import Information from "@/components/sections/Information";
import Research from "@/components/sections/Research";
import Follow from "@/components/sections/Follow";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>aalto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="overflow-hidden">
        <Hero />
        <SpotLight />
        <Events />
        <Explore />
        <Studies />
        <Information />
        <Research />
        <Follow />
      </main>
      <Footer />
    </>
  );
}
